const readyServices = [
  {
    title: 'Eris',
    subtitle: 'Документы',
    icon: '/images/icons/document.svg',
    bgColor: '#da125a',
    textColor: '#fff',
    alpha: false,
    colorAlpha: '',
    beta: true,
    clock: '',
    href: 'http://eris.bz/',
    desktopImage: '/images/ready/eris-computer.png',
    mobileImage: '/images/ready/eris-mobile.png',
    descriptionTitle: 'Корпоративный мессенджер для эффективных команд',
    descriptionSubtitle: 'Корпоративная рабочая область, удобные упоминания, обсуждения, чаты, расшифровка аудиосообщений',
    white: true,
  },
  {
    title: 'Bbook',
    subtitle: 'Автоматизация записи',
    icon: '/images/icons/calendar.svg',
    bgColor: '#c0ee0a',
    textColor: '#424242',
    alpha: true,
    colorAlpha: '#c0ee0a',
    href: '',
  },
  {
    title: 'VOL',
    subtitle: 'Корпоративный мессенджер',
    icon: '/images/icons/messanger.svg',
    bgColor: '#679afd',
    textColor: '#fff',
    alpha: true,
    colorAlpha: '#679afd',
    href: 'http://vol.bz/',
    desktopImage: '/images/ready/vol-computer.png',
    mobileImage: '/images/ready/vol-mobile.png',
    descriptionTitle: 'Генератор документов с гибкими шаблонами',
    descriptionSubtitle: 'Создание и управление шаблонами, автораспознавание документов, удобное хранилище, интеграция с CRM',
    white: true,
  },
  {
    title: 'Estraid',
    subtitle: 'База объектов недвижимости',
    icon: '/images/icons/base.svg',
    bgColor: '#1ee8d9',
    textColor: '#424242',
    alpha: false,
    colorAlpha: '#1ee8d9',
    clock: '',
    href: 'http://estraid.com/',
    desktopImage: '/images/ready/estraid-computer.png',
    mobileImage: '/images/ready/estraid-mobile.png',
    descriptionTitle: 'Управление базой объектов для агентств недвижимости',
    descriptionSubtitle: 'Управляйте проектами, объектами, застройщиками, созадавайте подборки для клиентов, удобная интеграция с CRM',
    white: false,
  },
  {
    title: 'Tolp',
    subtitle: 'Облачное хранилище',
    icon: '/images/icons/cloud.svg',
    bgColor: '#7e26f9',
    textColor: '#fff',
    alpha: true,
    colorAlpha: '#7e26f9',
    href: '',
  },
  {
    title: 'Tamer',
    subtitle: 'Таскер',
    icon: '/images/icons/task.svg',
    bgColor: '#19cca1',
    textColor: '#fff',
    alpha: true,
    colorAlpha: '#19cca1',
    href: '',
  },
  {
    title: 'Rite',
    subtitle: 'Международная АТС',
    icon: '/images/icons/ats.svg',
    bgColor:
      'linear-gradient(180deg, #35ff14 0%, rgba(255, 255, 255, 0) 100%), #01fed0',
    textColor: '#424242',
    alpha: true,
    colorAlpha: '#3fff31',
    href: '',
  },
];

export default readyServices;
