const readyServices = [
  {
    title: 'Eris',
    subtitle: 'Документы',
    icon: '/images/icons/document.svg',
    bgColor: '#da125a',
    textColor: '#fff',
    alpha: false,
    colorAlpha: '',
    clock: '',
    href: 'http://eris.bz/',
  },
  {
    title: 'Bbook',
    subtitle: 'Автоматизация записи',
    icon: '/images/icons/calendar.svg',
    bgColor: '#c0ee0a',
    textColor: '#424242',
    alpha: true,
    colorAlpha: '#c0ee0a',
    href: '',
  },
  {
    title: 'VOL',
    subtitle: 'Корпоративный мессенджер',
    icon: '/images/icons/messanger.svg',
    bgColor: '#679afd',
    textColor: '#fff',
    alpha: true,
    colorAlpha: '#679afd',
    href: 'http://vol.bz/',
  },
  {
    title: 'Estraid',
    subtitle: 'База объектов недвижимости',
    icon: '/images/icons/base.svg',
    bgColor: '#1ee8d9',
    textColor: '#424242',
    alpha: false,
    colorAlpha: '#1ee8d9',
    clock: '',
    href: 'http://estraid.com/',
  },
  {
    title: 'Tolp',
    subtitle: 'Облачное хранилище',
    icon: '/images/icons/cloud.svg',
    bgColor: '#7e26f9',
    textColor: '#fff',
    alpha: true,
    colorAlpha: '#7e26f9',
    href: '',
  },
  {
    title: 'Tamer',
    subtitle: 'Таскер',
    icon: '/images/icons/task.svg',
    bgColor: '#19cca1',
    textColor: '#fff',
    alpha: true,
    colorAlpha: '#19cca1',
    href: '',
  },
  {
    title: 'Rite',
    subtitle: 'Международная АТС',
    icon: '/images/icons/ats.svg',
    bgColor:
      'linear-gradient(180deg, #35ff14 0%, rgba(255, 255, 255, 0) 100%), #01fed0',
    textColor: '#424242',
    alpha: true,
    colorAlpha: '#3fff31',
    href: '',
  },
];

export default readyServices;
